### ISSUE TITLE
A change to the files are needed befor submitting

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-what-is-a-test#13]
needs to be a change to the files be fore submitting or you receive a message stating Your code looks the same as the lesson's. Please make changes and then try submitting again.

In this lesion you do not get told to make any changes. i just added a space to the file and save it and it let me submit with no issues.

**Comment by maxwellbenton** [comment]
Hi @deathheart14, 

Thank you for reporting this. We've updated this lesson to include additional instructions about making a change to the files before submitting, which should resolve this issue going forward.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.

Thank you!
