### ISSUE TITLE
Java Script >fucntions & scope > What Is A Test

### ISSUE THREAD

**Issue by sleepypioneer** [learn-co-curriculum/js-what-is-a-test#14]
Not sure what I have missed, but I have ran learn and the local test button has not gone green I therefore cannot submit and complete the lesson.

Best wishes
Jessica

**Comment by sleepypioneer** [comment]
This has resolved itself from logging on today. JG

**Comment by maxwellbenton** [comment]
Hi @sleepypioneer,

Glad to hear that everything was resolved. Thank you for taking the time to reach out and let us know about your experience!
