### ISSUE TITLE
Issue with console.log(message)

### ISSUE THREAD

**Issue by PeterCiavarella** [learn-co-curriculum/js-what-is-a-test#15]
I'm not sure if I am right, but i believe it should be `console.log('message')` instead of `console.log(message)` otherwise your message will not appear on the IDE.

**Comment by maxwellbenton** [comment]
Hi @PeterCiavarella,

Unfortunately, I was unable to replicate the issue you experienced. However, the contents of this lesson have recently been updated, and I can confirm that the `console.log` is behaving as intended now.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.

Thank you!
