### ISSUE TITLE
Error: 'Your code looks the same as the lesson's. Please make changes and then try submitting again.'

### ISSUE THREAD

**Issue by markbello** [learn-co-curriculum/js-what-is-a-test#16]
Error: `Your code looks the same as the lesson's. Please make changes and then try submitting again.`

Solution: I typed a blank space into README.md and saved it. The lesson didn't specify any changes to make, and the IDE threw an error because it expected something new to commit before letting me move on.

**Comment by maxwellbenton** [comment]
Hi @markbello,
 
Thank you for reporting this. We've updated this lesson to include instructions to make a change to the file contents in order for Learn to register completion, which should resolve this issue going forward.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.

Thank you!
