### ISSUE TITLE
Suggested Grammar Revision

### ISSUE THREAD

**Issue by wontgobeli** [learn-co-curriculum/js-what-is-a-test#18]
I'd suggest changing the "For many years, [if] statements is all we had though." line (paragraph two, sentence one) to "For many years [if] statements are all we had."

**Comment by maxwellbenton** [comment]
Hi @wontgobeli,

Thank you for reporting this. We've recently updated this lesson's contents and have changed this sentence based on your feedback.

Thank you for contributing to a Learn lesson!
