### ISSUE TITLE
General Ordering Issue

### ISSUE THREAD

**Issue by skmcloughlin** [learn-co-curriculum/js-what-is-a-test#2]
This lesson requires learners to run tests on code but does not mention the "learn" command to do so. 
I skipped ahead to find that.
Also, not sure if this is intentional or not, but some of the fixes were a bit tricky to ferret out.
I understand if that is part of the process though.

**Comment by NStephenson** [comment]
@aturkewi It looks like this lesson was intended to be a readme but shows up as a lab. Instructions on actually passing this lab are found the the following lesson as stated above.

**Comment by jmburges** [comment]
Converted this to a README. Hopefully that makes it more straight forward that I don't expect students to run `learn`
