### ISSUE TITLE
Cannot find module 'jsdom/lib/old-api'

### ISSUE THREAD

**Issue by Chovin** [learn-co-curriculum/js-what-is-a-test#20]
Running `learn` on this lesson shows the same behavior (error and fix) as described in https://github.com/learn-co-curriculum/js-what-is-a-test-lab/issues/11

Looking through learn-co-curriculum's repos that have "js" in the title, I found 28 repos listed below with the mocha-jsdom devDependency set as `"^1.1.0"`

I'm new to this TDD stuff as well as Mocha, but I'll try to see if the fix described in the 1st issue is enough to fix these as well and checkmark them once I confirm.

https://github.com/learn-co-curriculum/moving-things-with-javascript/pull/18 seems to suggest that more might be required?

### [edit]The repos have been checked following this methodology:
for each repo:
1. `npm install`; before = `npm test`
2. replace `"mocha-jsdom": "^1.1.0"` with `"mocha-jsdom": "~1.1.0"` in `package.json`
3. `npm install`; after = `npm test`
4. if 'old-api' is in before and not in after, check the box
 (note: there were none in this list with 'old-api' in after)

- [x] [js-ajax-intro-to-ajax-readme](https://github.com/learn-co-curriculum/js-ajax-intro-to-ajax-readme) - [#L28](https://github.com/learn-co-curriculum/js-ajax-intro-to-ajax-readme/blob/master/package.json#L28)
- [ ] [jsdom-mod-hide-and-seek-lab](https://github.com/learn-co-curriculum/jsdom-mod-hide-and-seek-lab) - [#L31](https://github.com/learn-co-curriculum/jsdom-mod-hide-and-seek-lab/blob/master/package.json#L31)
- [ ] [js-dom-and-events-events-deep-dive-readme](https://github.com/learn-co-curriculum/js-dom-and-events-events-deep-dive-readme) - [#L30](https://github.com/learn-co-curriculum/js-dom-and-events-events-deep-dive-readme/blob/master/package.json#L30)
- [x] [js-hashes-readme](https://github.com/learn-co-curriculum/js-hashes-readme) - [#L32](https://github.com/learn-co-curriculum/js-hashes-readme/blob/master/package.json#L32)
- [x] [phrg-js-ajax-advanced-ajax-lab](https://github.com/learn-co-curriculum/phrg-js-ajax-advanced-ajax-lab) - [#L28](https://github.com/learn-co-curriculum/phrg-js-ajax-advanced-ajax-lab/blob/master/package.json#L28)
- [x] [js-templates-advanced-templating-readme](https://github.com/learn-co-curriculum/js-templates-advanced-templating-readme) - [#L28](https://github.com/learn-co-curriculum/js-templates-advanced-templating-readme/blob/master/package.json#L28)
- [ ] [js-object-methods-lab](https://github.com/learn-co-curriculum/js-object-methods-lab) - [#L23](https://github.com/learn-co-curriculum/js-object-methods-lab/blob/master/package.json#L23)
- [x] [js-looping-and-iteration-foreach-lab](https://github.com/learn-co-curriculum/js-looping-and-iteration-foreach-lab) - [#L32](https://github.com/learn-co-curriculum/js-looping-and-iteration-foreach-lab/blob/master/package.json#L32)
- [x] [js-ajax-hitting-apis-lab](https://github.com/learn-co-curriculum/js-ajax-hitting-apis-lab) - [#L30](https://github.com/learn-co-curriculum/js-ajax-hitting-apis-lab/blob/master/package.json#L30), [#L37](https://github.com/learn-co-curriculum/js-ajax-hitting-apis-lab/blob/master/package.json#L37)
- [ ] [phrg-js-templates-advanced-templating-lab](https://github.com/learn-co-curriculum/phrg-js-templates-advanced-templating-lab) - [#L30](https://github.com/learn-co-curriculum/phrg-js-templates-advanced-templating-lab/blob/master/package.json#L30), [#L38](https://github.com/learn-co-curriculum/phrg-js-templates-advanced-templating-lab/blob/master/package.json#L38)
- [x] [phrg-js-templates-advanced-templating-readme](https://github.com/learn-co-curriculum/phrg-js-templates-advanced-templating-readme) - [#L28](https://github.com/learn-co-curriculum/phrg-js-templates-advanced-templating-readme/blob/master/package.json#L28)
- [x] [phrg-js-ajax-fetch-readme](https://github.com/learn-co-curriculum/phrg-js-ajax-fetch-readme) - [#L28](https://github.com/learn-co-curriculum/phrg-js-ajax-fetch-readme/blob/master/package.json#L28)
- [x] [phrg-js-templates-template-engines-lab](https://github.com/learn-co-curriculum/phrg-js-templates-template-engines-lab) - [#L30](https://github.com/learn-co-curriculum/phrg-js-templates-template-engines-lab/blob/master/package.json#L30), [#L38](https://github.com/learn-co-curriculum/phrg-js-templates-template-engines-lab/blob/master/package.json#L38)
- [ ] [phrg-js-dom-and-events-hide-and-seek-lab](https://github.com/learn-co-curriculum/phrg-js-dom-and-events-hide-and-seek-lab) - [#L31](https://github.com/learn-co-curriculum/phrg-js-dom-and-events-hide-and-seek-lab/blob/master/package.json#L31)
- [x] [js-what-is-a-test](https://github.com/learn-co-curriculum/js-what-is-a-test) - [#L32](https://github.com/learn-co-curriculum/js-what-is-a-test/blob/master/package.json#L32)
- [x] [js-dom-and-events-advanced-selectors-readme](https://github.com/learn-co-curriculum/js-dom-and-events-advanced-selectors-readme) - [#L30](https://github.com/learn-co-curriculum/js-dom-and-events-advanced-selectors-readme/blob/master/package.json#L30)
- [x] [js-ajax-fetch-readme](https://github.com/learn-co-curriculum/js-ajax-fetch-readme) - [#L28](https://github.com/learn-co-curriculum/js-ajax-fetch-readme/blob/master/package.json#L28)
- [ ] [js-templates-advanced-templating-lab](https://github.com/learn-co-curriculum/js-templates-advanced-templating-lab) - [#L30](https://github.com/learn-co-curriculum/js-templates-advanced-templating-lab/blob/master/package.json#L30), [#L38](https://github.com/learn-co-curriculum/js-templates-advanced-templating-lab/blob/master/package.json#L38)
- [x] [js-templates-template-engines-lab](https://github.com/learn-co-curriculum/js-templates-template-engines-lab) - [#L30](https://github.com/learn-co-curriculum/js-templates-template-engines-lab/blob/master/package.json#L30), [#L38](https://github.com/learn-co-curriculum/js-templates-template-engines-lab/blob/master/package.json#L38)
- [ ] [js-looping-and-iteration-foreach-readme](https://github.com/learn-co-curriculum/js-looping-and-iteration-foreach-readme) - [#L38](https://github.com/learn-co-curriculum/js-looping-and-iteration-foreach-readme/blob/master/package.json#L38)
- [x] [phrg-js-ajax-intro-to-ajax-readme](https://github.com/learn-co-curriculum/phrg-js-ajax-intro-to-ajax-readme) - [#L28](https://github.com/learn-co-curriculum/phrg-js-ajax-intro-to-ajax-readme/blob/master/package.json#L28)
- [ ] [node-js-testing](https://github.com/learn-co-curriculum/node-js-testing) - [#L35](https://github.com/learn-co-curriculum/node-js-testing/blob/master/package.json#L35)
- [ ] [js-dom-and-events-hide-and-seek-lab](https://github.com/learn-co-curriculum/js-dom-and-events-hide-and-seek-lab) - [#L31](https://github.com/learn-co-curriculum/js-dom-and-events-hide-and-seek-lab/blob/master/package.json#L31)
- [x] [js-rock-dodger-in-class](https://github.com/learn-co-curriculum/js-rock-dodger-in-class) - [#L28](https://github.com/learn-co-curriculum/js-rock-dodger-in-class/blob/master/package.json#L28)
- [ ] [js-dom-and-events-acting-on-events-lab](https://github.com/learn-co-curriculum/js-dom-and-events-acting-on-events-lab) - [#L26](https://github.com/learn-co-curriculum/js-dom-and-events-acting-on-events-lab/blob/master/package.json#L26)
- [x] [js-hoisting-readme](https://github.com/learn-co-curriculum/js-hoisting-readme) - [#L33](https://github.com/learn-co-curriculum/js-hoisting-readme/blob/master/package.json#L33)
- [ ] [phrg-js-dom-and-events-acting-on-events-lab](https://github.com/learn-co-curriculum/phrg-js-dom-and-events-acting-on-events-lab) - [#L26](https://github.com/learn-co-curriculum/phrg-js-dom-and-events-acting-on-events-lab/blob/master/package.json#L26)
- [x] [phrg-js-ajax-hitting-apis-lab](https://github.com/learn-co-curriculum/phrg-js-ajax-hitting-apis-lab) - [#L30](https://github.com/learn-co-curriculum/phrg-js-ajax-hitting-apis-lab/blob/master/package.json#L30), [#L37](https://github.com/learn-co-curriculum/phrg-js-ajax-hitting-apis-lab/blob/master/package.json#L37)

**Comment by Chovin** [comment]
should I PR these? 😰

**Comment by maxwellbenton** [comment]
Hi @Chovin,

Thank you for reporting this and providing a thorough list. We've updated all the lessons in this list to ensure this error is no longer occurring, which should resolve this issue.

Thank you for contributing to Learn!
