### ISSUE TITLE
Problem with directory 

### ISSUE THREAD

**Issue by dana0522** [learn-co-curriculum/js-what-is-a-test#22]
if i'm in the correct directory (AKA master directory js-what-is-a...), IDE tells me it cannot find this module. If i change the directory to be master folder->test, then the file executes fine. However, when i try 'learn' with this directory, it tells me the directory is not 'a Learn Lesson's directory.' And if I change it back to whatever it was before, I get the same error message again saying it cannot locate the module.. 

I was able to submit by typing out the entire directory. This has to be some sort of a bug. No one could help me with this.

**Comment by maxwellbenton** [comment]
Hi @dana0522,

Sorry to hear you were having difficulty with this lab. Unfortunately, I was unable to replicate the issue you experienced.  However, this lesson was recently updated and I can confirm that the learn commands are currently working from the main directory of this lesson.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.

Thank you!
