### ISSUE TITLE
Cannot Find Repo

### ISSUE THREAD

**Issue by harmful-bug** [learn-co-curriculum/js-what-is-a-test#24]
Hello! I'm getting this message when I open the IDE:

[17:43:12] ~
// ♥ learn open js-what-is-a-test-bootcamp-prep-000
Looking for lesson...
Hmm...Cannot find lesson with repo: js-what-is-a-test-bootcamp-prep-000. Pleasecheck your input and try again.
[17:43:15] ~
// ♥

My Wi-Fi connection is strong, and I've tried refreshing the page a few times.

Thank you,

~jesus

**Comment by maxwellbenton** [comment]
Hi @jesusnunezxoco,

Sorry to hear you were having difficulties getting this lesson to fork. Unfortunately, I was unable to replicate the issue you experience but can confirm that the lesson is currently opening in the IDE as expected. 

We apologize for any frustration this may have caused, but we appreciate you taking the time to reach out and let us know about your experience.
