### ISSUE TITLE
Suggestion, INCLUDE HOW TO VIDEOS! Screen Shares!

### ISSUE THREAD

**Issue by martyjones06** [learn-co-curriculum/js-what-is-a-test#27]
Just a suggestion, but I believe it would be of a huge help to include screen share videos of the processes along with spoken tutorials, this would prohibit some of the frustration of new students. 
                                           Thank you for reviewing!

**Comment by maxwellbenton** [comment]
Hi @martyjones06,

Thank you for providing this feedback. We have started to add video support to our materials and plan to continue to expand the availability of recorded content, which should help prevent some of the frustrations new students face.

We appreciate you taking the time to reach out and let us know about this!

Thank you!
