### ISSUE TITLE
Folder Missing?

### ISSUE THREAD

**Issue by catadabilis** [learn-co-curriculum/js-what-is-a-test#30]
When attempting to run _**node js/index.js**_ from the terminal using the macOS version of the Learn IDE (v3.0.0) I received the error _**Error: Cannot find module '/home/catamarsh/js-what-is-a-test-bootcamp-prep-000/js/index.js'.**_

Creating a folder named _**_js_**_ fixed the issue.

**Comment by catadabilis** [comment]
The above issue is related to the **_Getting Started_** section.

When trying to complete the challenge in **_The Tests_** section I had to move **_index.js_** out of the **_js_** folder in order to get the **_learn_** command to return the expected results to complete the lesson.

**Comment by lizbur10** [comment]
Thank you for providing feedback. We have clarified the lab instructions to address this issue.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
