### ISSUE TITLE
Manual Download to get files into Learn-IDE 

### ISSUE THREAD

**Issue by Aftershock06** [learn-co-curriculum/js-what-is-a-test#6]
Hey Guys, 

    I was working on this file and had to manually download the git into the .atom folder. Can you link it like the rest of the labs so that we can have access to files so that we can make the changes?

**Comment by maxwellbenton** [comment]
Hi @Aftershock06, 

Thank you for reporting this. We've updated this lesson and confirmed that it is now correctly recognizing this lesson as a lab and will automatically download all the lab contents when clicking `Open IDE` in Learn, which should resolve this issue.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience.
